export const TYPES = {
  Prefix: Symbol('Prefix'),
  AppRoot: Symbol('AppRoot'),
  Bot: Symbol('Bot'),
  BotGateway: Symbol('BotGateway'),
  BotComandsHandler: Symbol('BotComandsHandler'),
  BotUserChangeChannelHandler: Symbol('BotUserChangeChannelHandler'),
  LogHandler: Symbol('LogHandler'),
  MusicHandler: Symbol('MusicHandler'),
  WebService: Symbol('WebService'),
  Client: Symbol('Client'),
  SongQueue: Symbol('SongQueue'),
  YouTubeService: Symbol('YouTubeService'),
  BotComandplay: Symbol('BotComandPlay'),
  BotComandskip: Symbol('BotComandSkip'),
  BotComandstop: Symbol('BotComandStop'),
  BotComandlistar: Symbol('BotComandListar'),
  BotComanddesconectar: Symbol('BotComandDesconectar'),
  BotComandclearchat: Symbol('BotComandClearChat'),
  BotComandping: Symbol('BotComandPing'),
  BotComandhelp: Symbol('BotComandHelp'),
  BotComandexit: Symbol('BotComandExit'),
}
