export const TYPES = {
  Prefix: Symbol('Prefix'),
  Bot: Symbol('Bot'),
  BotGateway: Symbol('BotGateway'),
  BotComandsHandler: Symbol('BotComandsHandler'),
  LogHandler: Symbol('LogHandler'),
  MusicHandler: Symbol('MusicHandler'),
  WebService: Symbol('WebService'),
  Client: Symbol('Client'),
  SongQueue: Symbol('SongQueue'),
  YouTubeService: Symbol('YouTubeService'),
  BotComandPlay: Symbol('BotComandPlay'),
  BotComandSkip: Symbol('BotComandSkip'),
  BotComandStop: Symbol('BotComandStop'),
  BotComandListar: Symbol('BotComandListar'),
  BotComandDesconectar: Symbol('BotComandDesconectar'),
  BotComandClearChat: Symbol('BotComandClearChat'),
  BotComandPing: Symbol('BotComandPing'),
  BotComandHelp: Symbol('BotComandHelp'),
  BotComandExit: Symbol('BotComandExit'),
}
